apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: retrieve-build-image-info
spec:
  description: This task returns more detailed info about a model that has just been built and builds a url.txt file with all image tags to be pushed to
  workspaces:
  - name: images_url
    description: workspace where url.txt file is created
  params:
  - name: namespace
    type: string
    description: The namespace where the model was built
  - name: model-name
    type: string
    description: The name of the model
  - name: model-version
    type: string
    description: The version of the model built
  - name: buildah-sha
    type: string
    description: The built image digest
  - name: pipeline-run-uid
    type: string
    description: The pipeline run id that was run to build the model
  - name: candidate-image-tag-reference
    type: string
    description: The image tag references used when testing the image
  - name: target-image-tag-references
    type: array
    description: The image tag references used for the final built image
  steps:
  - name: get-image-sha
    image: registry.access.redhat.com/ubi9/skopeo
    args:
      - "$(params.target-image-tag-references[*])"
    script: |
      #!/usr/bin/env bash

      set -Eeuo pipefail

      echo -n "$(params.model-name)" | tee $(results.model-name.path) ;
      echo ;
      echo -n "$(params.model-version)" | tee $(results.model-version.path) ;
      echo ;
      export DOCKER_IMAGE_REF=$(skopeo inspect --format '{{.Name}}@{{.Digest}}' docker://$(params.candidate-image-tag-reference)) ;
      if [[ $DOCKER_IMAGE_REF != *"$(params.buildah-sha)"* ]]; then
        echo "Candidate image tag does not contain the correct manifest digest after push"
        exit 1 ;
      fi
      echo -n $DOCKER_IMAGE_REF | tee $(results.image-digest-reference.path) ;
      echo ;
      echo $(($(skopeo inspect --format '{{range .LayersData}}+{{.Size}}{{end}}' docker://$DOCKER_IMAGE_REF))) | tee $(results.image-size-bytes.path) ;
      echo ;
      skopeo inspect --format '{{.Created}}' docker://$DOCKER_IMAGE_REF | tee $(results.image-creation-time.path) ;
      echo ;
      skopeo inspect --format '{{index .Labels "io.buildah.version"}}' docker://$DOCKER_IMAGE_REF | tee $(results.buildah-version.path) ;
      echo ;
      echo -n "$@" | tee $(results.target-image-tag-references.path) ;
      echo ;
      # Set source and destination image URLs in results
      export SOURCE_IMAGE_URL="docker://${DOCKER_IMAGE_REF}"
      export DEST_IMAGE_URLS=""
      for target in "$2"; do
        DEST_IMAGE_URLS="${DEST_IMAGE_URLS} docker://${target}"
      done
      echo ;
      echo -n $SOURCE_IMAGE_URL | tee $(results.source-image-url.path) ;
      echo ;
      echo -n $DEST_IMAGE_URLS | tee $(results.dest-image-url.path) ;

  results:
  - name: source-image-url
    description: The source image URL that was inspected 
  - name: dest-image-url
    description: The destination image URL(s) where the image will be pushed
  - name: model-name
    description: The name of the model
  - name: model-version
    description: The version of the model
  - name: image-size-bytes
    description: The size of the image in bytes
  - name: image-creation-time
    description: The date and time the image was created at
  - name: buildah-version
    description: The version of buildah used to build the image
  - name: image-digest-reference
    description: The fully qualified image digest reference of the image
  - name: target-image-tag-references
    description: The fully qualified image reference that the image was pushed to (e.g. registry.example.com/my-org/ai-model:1.0-1)
