kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: rhoai-edge-pipelines
  app.kubernetes.io/part-of: rhoai-edge-pipelines
resources:
- tasks/
- pipelines/
- https://raw.githubusercontent.com/tektoncd/catalog/main/task/github-open-pr/0.2/github-open-pr.yaml
