apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: gitops-update-pipeline-bike-rentals-
  labels:
    tekton.dev/pipeline: gitops-update-pipeline
spec:
  params:
  - name: model-name
    value: bike-rentals-auto-ml
  - name: image-registry-repo
    value: quay.io/rhoai-edge/bike-rentals-auto-ml
  - name: image-digest
    value: sha256:c978e95d366ecf057be47dbee958b69f45720d7e71ba1a91c28f0e6b3572c670
  - name: gitServer
    value: https://github.com
  - name: gitApiServer
    value: api.github.com
  - name: gitOrgName
    value: username
  - name: gitRepoName
    value: ai-edge-gitops
  - name: gitRepoBranchBase
    value: main
  - name: gitTokenSecretName
    value: edge-user-1
  - name: yq-script
    value: |
      yq eval -i "(.images[] | select(.name == \"edge-model-template-image\").newName) = \"${IMAGE_NAME}\"" \
        acm/odh-edge/apps/bike-rental-app/kustomization.yaml
      yq eval -i "(.images[] | select(.name == \"edge-model-template-image\").digest) = \"${IMAGE_DIGEST}\"" \
        acm/odh-edge/apps/bike-rental-app/kustomization.yaml
  pipelineRef:
    name: gitops-update-pipeline
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
  - name: git-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: git-basic-auth
    secret:
      secretName: edge-user-1
