apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kserve-download-model
spec:
  description: This task is used to download a model folder from an S3 bucket. Credentials to allow the download of the model are stored in the `s3-secret` workspace.
  params:
  - name: model-name
    type: string
    description: The name of the folder that contains the model files 
  - name: s3-bucket-name
    type: string
    description: The name of the S3 bucket to be downloaded from
  - name: model-relative-path
    type: string
    description: The path from the root of the S3 bucket to the folder in which the model folder is located. Passing in an empty value means the model is stored at the root of the bucket
  results:
  - name: s3-url
    description: The S3 URL used to download the model
  steps:
  - name: download-model-s3
    image: quay.io/opendatahub/kserve-storage-initializer:v0.11.1.3
    script: |
      mkdir -p $(workspaces.workspace.path)/model_dir-$(params.model-name)/

      if [ -n "$(params.model-relative-path)" ]; then
        export S3_URL="s3://$(params.s3-bucket-name)/$(params.model-relative-path)/$(params.model-name)"
      else
        export S3_URL="s3://$(params.s3-bucket-name)/$(params.model-name)"
      fi

      echo -n $S3_URL | tee $(results.s3-url.path) ;

      if [ -n "$(workspaces.ssl-ca-directory.path)" ]; then
        export CA_BUNDLE_CONFIGMAP_NAME=ssl-ca-directory
        export AWS_CA_BUNDLE=$(workspaces.ssl-ca-directory.path)/ca-bundle.crt
      fi
      
      STORAGE_CONFIG="$(cat $(workspaces.s3-secret.path)/s3-storage-config)" /storage-initializer/scripts/initializer-entrypoint \
      $S3_URL \
      $(workspaces.workspace.path)/model_dir-$(params.model-name)/$(params.model-name)
  workspaces:
  - description: The workspace for the downloaded model
    name: workspace
  - name: s3-secret
    description: The workspace containing the S3 credentials needed to download the model
  - name: ssl-ca-directory
    description: |
      A workspace containing CA certificates, this will be used by the model download script to
      verify the peer with when fetching over HTTPS.
    optional: true
