kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- check-model-and-containerfile-exists/check-model-and-containerfile-exists.yaml
- kserve-download-model/kserve-download-model.yaml
- test-model-rest-svc/test-model-rest-svc.yaml
- retrieve-build-image-info/retrieve-build-image-info.yaml
- copy-model-from-pvc/copy-model-from-pvc.yaml
- yq-update/yq-update.yaml
- move-model-to-root-dir/move-model-to-root-dir.yaml
- sanitise-object-name/sanitise-object-name.yaml
- https://raw.githubusercontent.com/tektoncd/catalog/main/task/github-open-pr/0.2/github-open-pr.yaml
